requirements.txt
Problem:
CCCL has been updated to fix a memory leak and the pointer to it needs
to be updated.
Solution:
Update CCCL pointer to pull in fix.
=> Updated CCCL pointer.

f5_ctlr_agent/bigipconfigdriver.py
Problem: The customProfiles boolean was used to decide whether or not we should call delete on custom profiles. However, if customProfiles dict was empty, the boolean was set to false and we never finished cleaning up profiles. We don't need this boolean, we will always look to see if any profiles should be deleted.
Solution: Remove this boolean check to allow an empty customProfiles struct to still be processed and all remaining profiles get cleaned up.
=> Remove customProfiles boolean

agent-build-requirements.txt, agent-runtime-requirements.txt
Problem:
CCCL has been updated and the old pointer to it here needs to be
updated to point to the latest CCCL.
Solution:
Update CCCL pointer to point to latest CCCL.
=> Update CCCL Pointer.

agent-build-requirements.txt, agent-runtime-requirements.txt
Problem:
CCCL has been updated to place keys and certificates in
the managed partition.
Solution:
Update CCCL pointer to pull in the change of partition.
affects-branches: master
=> Updated CCCL pointer. (fixes #214)

agent-build-requirements.txt, agent-runtime-requirements.txt
Problem:
CCCL has been updated so the agent needs to point to that version.
Solution:
Update the agent to point to updated CCCL.
=> Update CCCL pointer

agent-build-requirements.txt, agent-runtime-requirements.txt
Used the security fix vulnerabilities commit id of f5-cccl to upgrade python packages to resolve CVEs.
=> Fix security vulnerabilities

f5_ctlr_agent/bigipconfigdriver.py
Problem: The agent requires LTM "resources" section to push NET configuration to BIG-IP, though LTM and NET managers implemented without inter dependencies. 
Solution: Add a global parameter, using which creation of LTM manager can be restricted and when there is no LTM manager, agent does not require LTM "resources" section.
Signed-off-by: Subba Reddy Veeramreddy <subbareddyv.uoh@gmail.com>
=> Add LTM disable feature

f5_ctlr_agent/bigipconfigdriver.py
Configure BIG-IP GTM objects with Add/update/Delete
=> Configure BIG-IP GTM objects (Add/Update/Delete)

f5_ctlr_agent/bigipconfigdriver.py
Fixed Issues:
CIS is unable to delete the EDNS CRD without health monitor.
CIS is unable to delete the health monitor for EDNS CRD without pool members.
Signed-off-by: Amit Gupta amitg2812@gmail.com
=> HM delete and EDNS CRD delete without HM bug fix

f5_ctlr_agent/bigipconfigdriver.py
Reduced API call for GTM deletion. GTM processing improvements.
Signed-off-by: Amit Gupta amitg2812@gmail.com
=> Reduced API call for GTM deletion

f5_ctlr_agent/bigipconfigdriver.py
Signed-off-by: Subba Reddy Veeramreddy <subbareddyv.uoh@gmail.com>
=> Add GTM preprocess to update monitor properties

f5_ctlr_agent/bigipconfigdriver.py
Added TCP health Monitor support.
Bugfix: CIS tries to remove the non-existing monitor from the GTM pool.
=> Added TCP health Monitor support

.gitignore, f5_ctlr_agent/bigipconfigdriver.py
Added SNIServerName support for BIGIPv16.1 and above versions.
=> Adding SNIServerName support for BIGIPv16.1 or more

f5_ctlr_agent/bigipconfigdriver.py
Added support for Exception Handling for GTM Class
=> GTM Exception Handling

f5_ctlr_agent/bigipconfigdriver.py
GTM log message typo error fix.
=> GTM log message typo error fix

f5_ctlr_agent/bigipconfigdriver.py
Signed-off-by: Vivek Lohiya <vklohiya@live.com>
=> Added support for multiple Health monitors in EDNS resource

f5_ctlr_agent/bigipconfigdriver.py
Fix for deleting multiple edns resources
=> Fix for deleting multiple edns resources

f5_ctlr_agent/bigipconfigdriver.py
Currently, CIS just attaches only secured GTM pool members ignoring to remove the oldGTMPoolmembers created by CIS if existing.  This fix ensures that CIS properly removes the old GTM pool members from the BIGIP.
=> Removing unused GTM PoolMembers created by CIS in old Versions

agent-runtime-requirements.txt
Signed-off-by: Vivek Lohiya <vklohiya@live.com>
=> Updating the python packages and f5-cccl repo

agent-build-requirements.txt, agent-runtime-requirements.txt
=> update cccl commit id

agent-build-requirements.txt, agent-runtime-requirements.txt
upgraded certifi package in cccl to handle CVE-2022-23491
=> upgrade certifi 

f5_ctlr_agent/bigipconfigdriver.py
Description: If disable-arp is set to true then skip updating ARP.
=> Skip ARP update when disable-arp is true

f5_ctlr_agent/bigipconfigdriver.py
Fix for static route recreation on restart
=> static route fix recreate

agent-build-requirements.txt, agent-runtime-requirements.txt, f5_ctlr_agent/bigipconfigdriver.py
Reverting the secure credentials for 2.19
=> Reverting the secure credentials for 2.19
